name: Build Nuitka Standalone Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install upx
          pip install -r requirements.txt


      - name: Install UPX
        run: |
          choco install upx -y

      - name: Get UPX binary path
        run: |
          $UPXPath = (Get-Command upx).Source
          echo "UPX_PATH=$UPXPath" >> $GITHUB_ENV

      - name: Build executable with Nuitka
        run: |
          python -m nuitka --standalone --python-flag=-O `
          --include-data-files=./favicon.ico=./favicon.ico `
          --include-data-files=./frpc.exe=./frpc.exe `
          --include-package=PyQt6 `
          --upx-binary=$UPX_PATH `
          --include-package-data=PyQt6 `
          --include-qt-plugins=styles,platforms,qml `
          --plugin-enable=pyqt6,upx `
          --follow-import-to=PyQt6,PyQt6.QtCore,PyQt6.QtGui,PyQt6.QtWidgets `
          --remove-output `
          --include-package=mcstatus `
          --include-package=requests `
          --windows-console-mode=disable `
          --include-package=psutil `
          --include-package=pyperclip `
          --include-package=ipaddress `
          --assume-yes-for-downloads `
          --output-dir=./build_output `
          --nofollow-import-to=psutil.tests.test_testutils `
          --nofollow-import-to=psutil.tests `
          --windows-icon-from-ico=./favicon.ico `
          --jobs=4 `
          ./CHMLFRP_UI.py

      - name: Check if output directory exists
        run: |
          $outputDir = "./build_output"
          if (Test-Path $outputDir) {
            Write-Host "Output directory exists, proceeding with compression."
          } else {
            Write-Error "Output directory not found at $outputDir"
            exit 1
          }

      - name: Compress build output
        run: |
          $currentDate = (Get-Date -Format "yyyy_MM_dd")
          $zipFileName = "CHMLFRP_UI_$currentDate.zip"
          Compress-Archive -Path "./build_output/*" -DestinationPath $zipFileName
          Write-Output "Compressed build output to $zipFileName"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CHMLFRP_UI-archive
          path: ./*.zip
          retention-days: 7
